### ISSUE TITLE
Loop in CollectingManifestResourceTransformer causes infinite loop with certain relocations

### ISSUE THREAD

**Issue by jkebinger** [basepom/basepom-policy#4]
I originally documented this problem against the Shade plugin itself [Issue](https://issues.apache.org/jira/projects/MSHADE/issues/MSHADE-453?filter=allissues)

For relocations like 

```xml
<relocation>
  <pattern>com.google.common</pattern>
  <shadedPattern>prefab.shaded.com.google.common</shadedPattern>
</relocation>
```
where the shaded pattern contains the original pattern, this [loop](https://github.com/basepom/basepom-policy/blob/master/src/main/java/org/basepom/maven/shade/CollectingManifestResourceTransformer.java#L196-L207) keeps calling the same relocator class until the value stops changing - but it never does because it can keep replacing the first instance of the original pattern in the shaded pattern.

So the string passed to SimpleRelocator just grows and grows and grows!

There's no docs indicating patterns like this are prohibited, in fact the [docs](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#relocations) have such a pattern as an example.

Why does that code need to apply the same relocator multiple times?

**Comment by hgschmie** [comment]
(wow, sorry. I did not pay attention to this repo in a long time)

The problem is that the pattern is wrong. It is not anchored (the first value `<pattern>` is not a string, but a regexp pattern) and the `.` wildcards are not escaped. This should be

```
<relocation>
  <pattern>^com\.google\.common</pattern>
  <shadedPattern>prefab.shaded.com.google.common</shadedPattern>
</relocation>
```

which will then only relocate the pattern once. 

I will add some code to limit the loop (and then fail the build).

**Comment by jkebinger** [comment]
Thank you!
